#!/usr/bin/perl
# POD {{{
=head1 NAME

dbc - Find all Dropbox conflict files within a directory and handle them inteligently

=head1 SYNOPSIS

	dbc [options]

	This program locates all files labeled as conflicting by Dropbox and tries to apply inteligent rules to handle them.
	If the files conflict in a way that cannot be resolved the user is shown a diff and asked to fix the changes.

=over
	
=head1 OPTIONS

=over 8

=item B<--dp>

=item B<--diffpreview>

Specify the method used when showing the file diffs.

Valid methods;
	* Auto - Will run though the below in order and use the first valid method
	* Diff - Use the standard 'diff' program

Variables used in the command can be:

=over

=item B<$base>

The basic file name (and potencial perfect original file) to merge all conflicts into.

=item B<$peer>

The conflict file of the found Dropbox base file.

=back

=item B<-d>

=item B<--delete>

Delete all conflict files (assumes the user has already done a scan with '-l' first).

=item B<--exclude>

=item B<-x>

Exclude a partiqular file or directory from the scan.

This is mainly usedx to exclude Dropbox meta files like .dropbox.cache

=item B<--force>

=item B<-f>

Force attempting to deal with nested conflicts.
Should a file contain multiple levels of conlict, dbconflicts will not attempt to merge the file unless this flag is specified.

=item B<-l>

=item B<--list>

Display a list of conflicted files but do nothing.
Implies '-n'.

=item B<-t>

=item B<--temp>

Specify a list of temp files to delete silently during the scanning process.

=item B<-v>

=item B<--verbose>

Be more verbose when outputting information to STDERR.
Specify multiple times to increase verbosity.

=head1 DESCRIPTION

A command line tool for the manipulation of Dropbox conflict files.

=head1 EXAMPLES

=over

=item B<dbconflicts -l>

List all conflicted files in this directory.

=back

=head1 TODO

	* Detect if file content is binary
	* Support GUI merging

=head1 BUGS

Quite probably.

Please report to author when found.

=head1 AUTHOR

Matt Carter <m@ttcarter.com>

=cut
# }}} POD

package dbconflicts;
our $VERSION = '0.1.0';

# Header {{{
use feature 'switch';
use Digest::MD5::File qw/file_md5_hex/;
use File::Basename;
use File::DirWalk;
use MC::Input::Cli;
use IO::Handle;
use Getopt::Long;
use Text::Glob qw/match_glob glob_to_regex/;
Getopt::Long::Configure('bundling', 'ignorecase_always', 'pass_through');
STDERR->autoflush(1); # } Flush the output DIRECTLY to the output buffer without caching
STDOUT->autoflush(1); # }

use Data::Dump; # FIXME: Debugging modules
# }}} Header

our $diffcmd = q/vimdiff '$original' '$conflict'/;
our $dryrun, $delete;
our @exclude = qw/.dropbox.cache .dropbox/;
our @temp = qw/.*.swp/;
my @count_order = qw/total_files total_dirs conflicts skipped_binaries nested_conflicts missing_base deletes auto_deletes temp_files/;
my $diffpreview = 'auto';
my @diffpreview;
our %counts = map { $_ => 0 } @count_order;

my $list, $force;
GetOptions(
	# Global options
	'delete|d' => \$delete,
	'diffcmd|dc=s' => \$diffcmd,
	'force|f' => \$force,
	'diffpreview|dp=s' => \$diffpreview,
	'list|l' => \$list,
	'dryrun|n' => \$dryrun,
	'temp|t=s'=> \@temp,
	'verbose|v+' => \$verbose,
	'exclude|x=s' => \@exclude,
);
$dryrun = 1 if $list;
if ($diffpreview eq 'auto') { # Determine -diffpreview from first one that matches
	if (-x '/usr/bin/docdiffxxx') {
		$diffpreview = q/docdiff -y --suppress-common-lines %BASE %PEER/;
	} elsif (-x '/usr/bin/diff') {
		$diffpreview = q/diff -y --suppress-common-lines %BASE %PEER/;
	} else {
		$diffpreview = q/echo 'No diff previewer installed'/;
	}
}
say(2, "Using --diffpreview: $diffpreview");

@temp = map { $_ = glob_to_regex($_) } @temp; # Convert text globs to RegExps

my $walker = new File::DirWalk;
$walker->onFile(sub {
	my ($_) = @_;
	our $delete;
	our %conflicts, @temp, %counts;
	my $base, $box, $date, $suffix;

	$counts{total_files}++;

	foreach my $glob (@temp) {
		my $dir = dirname($_);
		$_ = basename($_);
		if (m/$glob/i) {
			say(0, "$dir/$_") if $list;
			unlink("$dir/$_") unless $dryrun;
			$counts{temp_files}++;
			return File::DirWalk::SUCCESS;
		}
	}

	return File::DirWalk::SUCCESS unless ($base, $box, $date, $suffix) = (m/^(.+?) \((.+?)'s conflicted copy ([0-9-]{10})(?: \([0-9]+\))?\)(.*)$/);
	$base = $base . $suffix;
	say(3, "Found conflict file: $base");
	if (!$force and $base =~ /conflicted copy/) {
		say(0, "Too many layers of conflict for file: '$base' - Use '-f' to force merging.");
		$counts{nested_conflicts}++;
		return File::DirWalk::SUCCESS;
	}
	unless (-e $base) {
		$counts{missing_base}++;
		say(1, "Base file missing for conflict '$_' - expecting base '$base'");
		return File::DirWalk::SUCCESS;
	}
	if (!$delete and (-B $base or -B $peer)) {
		$counts{skipped_binaries}++;
		say(1, "Binary file: $base. Skipping");
		return File::DirWalk::SUCCESS;
	}
	if ($delete) { 
		say(1, "Delete conflict: $_");
		$counts{deletes}++;
		unlink($_) unless $dryrun;
		return File::DirWalk::SUCCESS;
	}
	$counts{conflicts}++;
	push @{$conflicts{$base}}, $_;
		
	return File::DirWalk::SUCCESS;
});
$walker->onDirEnter(sub {
	our @exclude;
	my $dir = shift;
	say(2, "Scanning dir $dir");
	$counts{total_dirs}++;
	$base = basename($dir);
	if (grep { $_ eq $base } @exclude) {
		say("Exclude: $dir");
		return File::DirWalk::PRUNE;
	}
	return File::DirWalk::SUCCESS;
});
$walker->onDirLeave(sub {
	our %conflicts;
	our $diffcmd;
	our $dryrun;
	while (my($base, $peers) = each %conflicts) {
		say(0, $base) if $list;
		say(1, "Processing conflicts for '$base' (" . scalar(@peers) . " peers)");
		foreach $peer (@{$peers}) {
			my $basemd5 = file_md5_hex($base);
			my $peermd5 = file_md5_hex($peer);
			say(3, "MD5 compute. Base = $basemd5 Peer = $peermd5");
			if ($basemd5 eq $peermd5) {
				say(1, "Base and peer are identical. Deleting peer '$peer'");
				$counts{auto_deletes}++;
				unlink($peer);
				next;
			}

			if ($dryrun) {
				say(1, "Dry run mode. Not doing anything");
			} else { # Not in dry run
				say(0, "File    : $base");
				say(0, "Conflict: $peer");
				say(0, "Diff:");
				say(0);
				my $_ = $diffpreview;
				s/%BASE/\Q$base\E/g;
				s/%PEER/\Q$peer\E/g;
				say(2, "Diff preview cmd: $_");
				say(0, system($_));
				say(0);
				given (ask('Command', '/', qw/< > v e s \/ d ?/)) {
					when ('?') { # Show help
						say(0, <DATA>);
						redo;
					}
					when (/</) { # Use left
						unlink($peer);
					}
					when (/>/) { # Use right
						unlink($base);
						rename($peer, $base);
					}
					when ('d') { # Delete both
						unlink($base);
						unlink($peer);
					}
					when (m!s|/!) {
						next;
					}
					when (/v|e/) {
						eval { # Calculate merge command
							# Special shell escape replacements
							my($original, $conflict) = ($base, $peer);
							$original =~ s/'/'\\''/g; # FIXME: This is a totally stupid way of escaping shell args
							$conflict =~ s/'/'\\''/g;
	
							unless ($dryrun) {
								my $cmd = eval("return \"$diffcmd\"");
								say(3, "Merge - Exec: $cmd");
								system($cmd);
								say(1, "Finished merge operation");
								say(0);
								redo;
							}
						};
						if ($? != 0) {
							say(1, "Diff error. Skip '$peer'");
							next;
						}
					}
					default { redo }
				}
				say(0);
			}
		}
	}
	%conflicts = ();
	return File::DirWalk::SUCCESS;
});


@ARGV = qw/./ unless @ARGV; # Default to '.' if no specific dir is requested
foreach (@ARGV) {
	say(1, "Scan dir $_");
	our %conflicts;
	$walker->walk($_);

	foreach (@count_order) {
		my $nice_key = ucfirst($_);
		$nice_key =~ tr/_/ /;
		say(1, "$nice_key = $counts{$_}") if $counts{$_} > 0;
	}
}

# Data contains help screen
__DATA__
COMMAND HELP
?	Help		Display this help screen
<	Use Left	Use file on left (original base name)
>	Use Right	Use file on right (conflicting name)
v,e	Editor		Show in editor
/,s	Skip		Move onto next file
d	Delete both	Delete both the left and right files
